import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: [ neobrutalism],
      variables: {
        colorPrimary: '#323232',
        colorText: 'black',
        colorInputText: 'black',
        colorInputBackground: 'white',
      },
    }}
    >
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  
  );
}
